spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mavingue
    username: root
    password: 070239
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format-sql: true
    database: mysql
